### ISSUE TITLE
Cleaning of batch training scripts

### ISSUE THREAD

**Issue by AdityaKane2001** [ankit-vaidya19/ViT_exploration#1]
@ankit-vaidya19 

Please make the following changes in the batch training scripts

1. Add sensible and repeated defaults to train.py and omit them in the .sh files.
2. For each batch scripts, accept positional arguments (see [here](https://refine.dev/blog/bash-script-arguments/#understanding-positional-parameters)) for data dir and save dir, since they will be different on my system.

Close this issue when these are completed. Tag me in the closing comment.

**Comment by ankit-vaidya19** [comment]
@AdityaKane2001 
Have done the requested changes. Added the modified files to a new branch.
